1042 create card child component
gnosis/gp-ui pull request #581
Opened 2021-08-11 10:29 UTC by stackseeder

2021-08-11 21:17 UTC, alfetopito reviewed
One minor comment regard file name.

Otherwise, looks good!

I'll ask @alongoni and @biocom to review regarding the CSS though, as I feel like the texts are not centered, but I'm no qualified to make them so.

2021-08-11 21:17 UTC, alfetopito commented on src/components/common/Card/cardContent.tsx
> +export const CardContent: React.FC<CardContentProps> = ({ label, value, hint, status, ...rest }): JSX.Element => {
Make the file name also PascalCase like the component

2021-08-11 22:20 UTC, alongoni commented
> One minor comment regard file name.
> 
> Otherwise, looks good!
> 
> I'll ask @alongoni and @biocom to review regarding the CSS though, as I feel like the texts are not centered, but I'm no qualified to make them so.

Maybe we can center the texts using:
```
    display: flex;
    align-items: center;
    justify-content: center;
```
I'll try to fix that with Ivica-

2021-08-11 22:22 UTC, alongoni requested changes

2021-08-11 22:22 UTC, alongoni commented on src/components/common/Card/cardContent.tsx
> +    margin-bottom: 0px;
`margin: 0;
`
In order to center the content.

2021-08-16 20:32 UTC, alfetopito commented on src/components/common/Card/cardContent.tsx
> +export const CardContent: React.FC<CardContentProps> = ({ label, value, hint, status, ...rest }): JSX.Element => {
Still not resolved :)

2021-08-30 12:38 UTC, stackseeder commented on src/components/common/CardRow/CardRow.stories.tsx
> +      <Card xs={4} sm={4} md={4} lg={4}>
It was intention to make the last card different from others but I've made a slight mistake. I've fixed it.

2021-08-30 12:39 UTC, stackseeder commented on src/components/common/Card/CardContent.tsx
> +          {icon1} &nbsp;{label1}
I've fixed it.

2021-08-31 20:46 UTC, alfetopito commented
@stackseeder I've merged the parent PR. Let me know once you addressed the conflicts to review it again

2021-09-01 12:21 UTC, alongoni approved these changes
Looks good!! :+1:

2021-09-01 17:34 UTC, alfetopito approved these changes

2021-09-02 09:15 UTC, ramirotw approved these changes

2021-09-02 16:29 UTC, merged